[AutoBuilder] New build Sun 16 May 2021 10:15:20 AM EDT

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,4 +1,25 @@
 #!/bin/bash
 
-ant -buildfile ./ant/build.xml clean build package-jar
+#Merge the two sources
+cp -r src/* /home/connor/eclipse-workspace/NuovoLauncher/src 1>&2> /dev/null
 
+if [ $? -ne 0 ]; then
+    echo "Error! Merge failed. Please see log file."; exit $?
+fi
+
+ant -buildfile ./ant/build.xml clean build 1>&2> /dev/null
+
+if [ $? -ne 0 ]; then
+    echo "Error! Build failed"; exit $?
+fi
+
+ant -buildfile ./ant/build-final.xml create_run_jar 1>&2> /dev/null
+
+if [ $? -ne 0 ]; then
+    echo "Error! Build failed."; exit $?
+fi
+
+#push changes
+git add *
+git commit -m "[AutoBuilder] New build $(date)"
+git push -u origin master
